object Versions {
    const val coreKtx = "1.12.0"
    const val compose = "1.8.0"
    const val composeBom = "2023.03.00"
    const val lifecycleRuntime = "2.6.2"
    const val appCompact = "1.6.1"
    const val material = "1.10.0"
    const val hilt = "2.48.1"
    const val hiltCompiler = "1.0.0"
    const val material3 = "1.1.2"
    const val hiltNavigationCompose = "1.0.0"
    const val navigationCompose = "2.7.4"
    const val logginginterceptor = "4.8.1"
    const val moshiConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val gsonConverter = "2.9.0"
    const val okhttp = "5.0.0-alpha.11"
    const val retrofit = "2.9.0"
    const val coroutines = "1.7.3"
    const val coilImageLoader = "2.0.0-rc01"
    const val composeUIVersion = "1.5.4"
    const val junit = "4.13.2"
    const val junitExt = "1.1.5"
    const val junitJupiter = "5.8.1"
    const val mockitoCore = "5.7.0"
    const val mockitoInline = "3.11.2"
    const val junitKtx = "1.1.5"
    const val archTesting = "2.2.0"
    const val coroutineTesting = "1.7.3"
    const val mockitoKotlin = "2.2.0"
    const val espressoCore = "3.5.1"

}
